### ISSUE TITLE
Maybe dont expose environment keys in your repo?

### ISSUE THREAD

**Issue by developerJuiceLozzoc** [millelog/plant-water-array#1]
https://github.com/millelog/plant-water-array/blob/35f50aee433cbc810b5646a21eb76902addc3070/embeded-src/main.py#L10

**Comment by millelog** [comment]
Ah thank you! The plan is to have the ESP32 host its own wifi to connect to and configure with these secrets when you first set them up. Was doing this for testing and didn't realize I committed it.

Resolved with commit and pruned from git history: https://github.com/millelog/plant-water-array/commit/48cd8716637532b7836a2b9f8a80c8a77febaf37

Going to delete this issue so the secret isn't in this thread either.
